### Common

spring:
  application:
    name: UnloadBrain
  profiles:
    active: dev
  jpa:
    generate-ddl: false
  resources:
    add-mappings: false

logging:
  level:
    root: INFO


---

### Prod profile

spring:
  profiles: prod
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/openblog}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}
  jpa:
    hibernate:
      ddl-auto: validate

logging:
  level:
    com.unloadbrain: INFO



---

### Dev profile

spring:
  profiles: dev
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: ${DB_URL:jdbc:h2:mem:openblog;DB_CLOSE_ON_EXIT=FALSE;MODE=MYSQL}
    username: sa
    password:
    driver-class: org.h2.Driver
    jpa:
      show-sql: true

logging:
  level:
    com.unloadbrain: DEBUG

